### ISSUE TITLE
Specification: Remove multiple currency option

### ISSUE THREAD

**Issue by lkngtn** [1Hive/payroll-app#1]
One of the biggest sources of complexity in the payroll app is enabling employees to choose which asset or mix of assets they want to accept each period. This requires relying on a price oracle for each asset and imposes an unnecessary treasury management / budgeting challenge on the organization.  

Rather than allow users to select from eligible assets we should simply things by only supporting a single asset.

**Comment by sembrestels** [comment]
Do we still support a price oracle feed, or we give away a fixed amount of tokens (simple but not so good for non-stable coins)?

**Comment by lkngtn** [comment]
I would advocate removing the price oracle feed. 

Keep things as simple as possible and focused on the idea of someone having the option to either have their agreed upon salary in a "Cash" asset eg a stable coin, or get tokens/rep/equity based on a multiple of that.

**Comment by rperez89** [comment]
Closed via #26
