### ISSUE TITLE
UI modernization

### ISSUE THREAD

**Issue by sembrestels** [1Hive/payroll-app#14]
Continue modernization begun in #9:

* [ ] Modernize tables (use DataView)
* [ ] Modernize filters (use DateRangePicker and others)
* [ ] Modernize Transaction label (use TransactionBadge)

**Comment by rperez89** [comment]
@sembrestels was this task done in your PR?

**Comment by sembrestels** [comment]
No, this is what I left as a good first issue for developers who want to begin to collaborate with us. @vivianedias was interested, I'm not sure if she wants to take that.

**Comment by vivianedias** [comment]
yes, I'll take it @sembrestels!

**Comment by rperez89** [comment]
> yes, I'll take it @sembrestels!

awesome! do you think that you might be able to do this in the next two weeks?  let me know if you want to be included on our planning meetings :)

**Comment by vivianedias** [comment]
@rperez89 i'll start today and would love to be included in the meetings!!

**Comment by rperez89** [comment]
@vivianedias tonight i will take a look because some of the work was already done by A1, will review it and create new task if needed!

**Comment by fabriziovigevani** [comment]
closed by #43
