### ISSUE TITLE
New design for team key stats

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#17]
Since we are not using anymore the USD , we need to create a new component that displays the stats for the payment token and the equity

**Comment by fioreb** [comment]
![Payroll - Team Payroll](https://user-images.githubusercontent.com/61423083/75819477-8579cf00-5d79-11ea-80d0-ffa80ff0c38d.png)

**Comment by sembrestels** [comment]
We would still go with a table right? In the call we said that having "cards" for users was an exploriation Pati was doing, but, we were maintaining the table, as it is [here](https://www.figma.com/proto/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=4%3A3902&scaling=min-zoom).

**Comment by fioreb** [comment]
Oh yes, sorry I should upload that file! I will change the adjustments to avoid confusion.

**Comment by fioreb** [comment]
![Payroll](https://user-images.githubusercontent.com/61423083/75885356-206bbb00-5e05-11ea-9576-4953f9837230.png)

**Comment by lkngtn** [comment]
I think we can remove the exchange rate column from this. 

There is an emphasis on burn rate, but with the deferred compensation model this is not strictly accurate. I might rephrase that to Monthly Payroll Liability rather than burn rate. 

I think we also want to show "issuance" (for deferred equity compensation) if we are going to show "total paid".

**Comment by fioreb** [comment]
I worked on the changes, not sure if I understand correctly and the "Issuance" on the first box is correct.
I add the side panel to edit the Equity Option too.

**Main page:**
![Payroll - Main Team payroll](https://user-images.githubusercontent.com/61423083/76119915-22817580-5fcf-11ea-8667-0e01ce67cd47.png)

**Edit Equity Option:**
![Payroll - Edit Equity Option](https://user-images.githubusercontent.com/61423083/76119898-1dbcc180-5fcf-11ea-8500-e89486835317.png)

Please let me know your thoughts, thanks!

**Comment by rperez89** [comment]
> I worked on the changes, not sure if I understand correctly and the "Issuance" on the first box is correct.
> I add the side panel to edit the Equity Option too.
> 
> **Main page:**
> ![Payroll - Main Team payroll](https://user-images.githubusercontent.com/61423083/76119915-22817580-5fcf-11ea-8667-0e01ce67cd47.png)
> 
> **Edit Equity Option:**
> ![Payroll - Edit Equity Option](https://user-images.githubusercontent.com/61423083/76119898-1dbcc180-5fcf-11ea-8500-e89486835317.png)
> 
> Please let me know your thoughts, thanks!

Just an small comment i think that the Issuance should be represented in Token amounts rather than usd price right ? @lkngtn 
Something similar to what we have on the finance app

<img width="1166" alt="Screen Shot 2020-03-17 at 11 47 32 AM" src="https://user-images.githubusercontent.com/11763623/76868043-1efab380-6845-11ea-93a4-c583c8de406c.png">
what do you guys think?

**Comment by fioreb** [comment]
> > I worked on the changes, not sure if I understand correctly and the "Issuance" on the first box is correct.
> > I add the side panel to edit the Equity Option too.
> > **Main page:**
> > ![Payroll - Main Team payroll](https://user-images.githubusercontent.com/61423083/76119915-22817580-5fcf-11ea-8667-0e01ce67cd47.png)
> > **Edit Equity Option:**
> > ![Payroll - Edit Equity Option](https://user-images.githubusercontent.com/61423083/76119898-1dbcc180-5fcf-11ea-8500-e89486835317.png)
> > Please let me know your thoughts, thanks!
> 
> Just an small comment i think that the Issuance should be represented in Token amounts rather than usd price right ? @lkngtn
> Something similar to what we have on the finance app but maybe without the token icon
> 
> <img alt="Screen Shot 2020-03-17 at 11 47 32 AM" width="1166" src="https://user-images.githubusercontent.com/11763623/76868247-5e290480-6845-11ea-97a6-e2563d1742c6.png">
> 
> also what do you think about splitting the available salary box into something like this?
> 
> i have the feel that there is to much information there, and maybe add some icons to each info to make it cool!
> 
> <img alt="Screen Shot 2020-03-17 at 11 50 37 AM" width="520" src="https://user-images.githubusercontent.com/11763623/76868417-a7795400-6845-11ea-84f3-ecccfd4c1d90.png">

Yeah! I think icons could work, I can work on that!
I think maybe the Salary Burn Rate box has a lot of info too.

**Comment by fioreb** [comment]
I worked on the changes.
For the issuance box, I think the icon should be the icon of the token that each organization has set, for this case I design a new one for the Honey Token because we didn't have one yet, but we can change it.

Let me know your thoughts, thanks!

![Payroll - Main Team payroll (1)](https://user-images.githubusercontent.com/61423083/77957708-453f3b00-72aa-11ea-96e0-2f284ec403b2.png)

**Comment by rperez89** [comment]
> I worked on the changes.
> For the issuance box, I think the icon should be the icon of the token that each organization has set, for this case I design a new one for the Honey Token because we didn't have one yet, but we can change it.
> 
> Let me know your thoughts, thanks!
> 
> ![Payroll - Main Team payroll (1)](https://user-images.githubusercontent.com/61423083/77957708-453f3b00-72aa-11ea-96e0-2f284ec403b2.png)

you made it!! i am in love with this new design, what do you think @lkngtn @willjgriff ?

**Comment by lkngtn** [comment]
Love the Bee icon, though I think in practice we would want to use something generic for that icon. 

Also, question regarding the "base asset salary" and "equity asset salary", is this taking into account the users preferences on the split, or is it showing what the total would be if they choose one hundred percent in that category?

**Comment by rperez89** [comment]
mhh since [here](https://github.com/1Hive/payroll-app/issues/18) we are not setting any preference about how they want to split it we might want to just remove that equity column.
The split choose is made at the payroll request time right?
