### ISSUE TITLE
Add new Employee/Entity 

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#18]
We need design for the new form (we are not going to ask for the name)

We also need to do a refactor for this screen since is using an old React version and as we touch components will be good to do a cleanup and stick to the 1hive-aragon new coding styles.

- [ ] designs changes needed #30 and #31
- [ ] add removed validations on #15

**Comment by fioreb** [comment]
![Payroll - New Employee](https://user-images.githubusercontent.com/61423083/75819272-2451fb80-5d79-11ea-917c-9be16fd4352e.png)

**Comment by sembrestels** [comment]
I think account address would not go there (as entity is already that address). I also would like to see the asset we are allocating in the Salary in the label (something like `Salary (DAI)`).

We should change the Employee and Salary labels for other more aligned with the new vision of the app. Would we go for `slice` or `allocation` instead of `salary`?

**Comment by rperez89** [comment]
@lkngtn about the salary field here, is it going to be represented in usd value? if that is the case if the user select to get their payroll in 50% DAI and 50% equity and let's say that the salary is 5000, we know that we need to send 2500 DAI but how do we know how much of the org token we need to mint? i mean how are we going to know the conversion between Dollar and the org token?

**Comment by lkngtn** [comment]
> @lkngtn about the salary field here, is it going to be represented in usd value? if that is the case if the user select to get their payroll in 50% DAI and 50% equity and let's say that the salary is 5000, we know that we need to send 2500 DAI but how do we know how much of the org token we need to mint? i mean how are we going to know the conversion between Dollar and the org token?

This is where the multiplier fits in, the equity tokens won't have a "fair market value" as they will be unlikely to have any meaningful liquidity. Instead the organization will offer a multiplier accounting for the risk associated with taking the equity option instead of cash.

**Comment by rperez89** [comment]
ohhh i see , so let;s say that the base salary is 5000 DAI the user selects 50% in DAI and the rest in equity and we have a multiplier of 4x, we are going to mint 2500 x 4 tokens?

**Comment by willjgriff** [comment]
> We should change the Employee and Salary labels for other more aligned with the new vision of the app. Would we go for `slice` or `allocation` instead of `salary`?

Is there literature somewhere regarding the "new vision of the app"? Or can you give me a brief? Typically I think using common terminology is best for UX. Employee and Salary are fairly common when referring to Payroll, and I think quickly understood. I'm not so sure about 'slice' or 'allocation'.

**Comment by rperez89** [comment]
> > We should change the Employee and Salary labels for other more aligned with the new vision of the app. Would we go for `slice` or `allocation` instead of `salary`?
> 
> Is there literature somewhere regarding the "new vision of the app"? Or can you give me a brief? Typically I think using common terminology is best for UX. Employee and Salary are fairly common when referring to Payroll, and I think quickly understood. I'm not so sure about 'slice' or 'allocation'.

I think that there could be some legal implications about naming it as "employee" and "salary" now that a DAO can be mapped to the real world, i think that was the reason why we wanted to change it. But we can find another terminology for that , what do you think?

**Comment by lkngtn** [comment]
> Is there literature somewhere regarding the "new vision of the app"? Or can you give me a brief? Typically I think using common terminology is best for UX. Employee and Salary are fairly common when referring to Payroll, and I think quickly understood. I'm not so sure about 'slice' or 'allocation'.

This was a conversation that came up on keybase, I think the decision was to stick with payroll/employee for now and if we get feedback at somepoint we can consider using different terminology. I had originally brought up the concern because the term "employee" and "salary" can have some very specific legal meaning in certain jurisdictions which might prove to be problematic.

**Comment by rperez89** [comment]
@lkngtn about that change that we made about the address, should we rename again the `Entity` to `Employee Address`? or just `Address`

**Comment by rperez89** [comment]
@lkngtn at some point we decided to remove the Employee name from this form, is this still valid?

**Comment by fabriziovigevani** [comment]
closed by #43
