### ISSUE TITLE
Specification: Support Minting Tokens

### ISSUE THREAD

**Issue by lkngtn** [1Hive/payroll-app#2]
A more interesting case for wanting to give users an option between receiving their payroll in different assets is the distinction between "cash" and "equity", where a user may opt to receive a portion of their agreed upon salary as tokens/rep/equity. 

Unlike receiving different capital assets this provides a relatively unique benefit for both the organization and the user. For early stage organization there may be relatively little cash on hand, but the organization can negotiate a market based compensation arrangement and the user can receive equity at a fixed (or dynamic) rate. 

This helps organizations bootstrap, while being fair and equitable to contributors who are forgoing a fair market salary. 

Unlike #1 this option would not require pricefeeds as token option can be priced relative to the base currency as it does not itself have a fair market value. 

- An organization should be able to adjust the multipliers or turn off the option via a role. 
- The rate offered for minting tokens is relative to the base currency amount, and would be a multiplier. eg if the user has a salary of 100DAI and the multiplier is 4x they can mint up to 400 of the equity asset per period. 
- The multiplier is fixed and can be updated with a role.

**Comment by fioreb** [comment]
![Payroll - Edit request salary](https://user-images.githubusercontent.com/61423083/75819756-f325fb00-5d79-11ea-88f0-68079be53840.png)
![Payroll - Edit salary split 2nd option](https://user-images.githubusercontent.com/61423083/75819768-f6b98200-5d79-11ea-8e4b-4704402d2769.png)
![Payroll](https://user-images.githubusercontent.com/61423083/75819770-f7521880-5d79-11ea-9db3-21d82c3d8445.png)

**Comment by sembrestels** [comment]
I would prefer to have just one panel, in which you can set up the percentage and request salary at the same time.

Is there any good reason to keep them separated? Are we planning to add more options in the _Edit salary allocation_ panel?

**Comment by fioreb** [comment]
We discuss with Gabi about that matter: the problem of having only one panel it's the user probably won't change the salary allocation as many times as he will request the salary, maybe it's not necessary to have everything in one panel, to avoid an excess of information.

But if we prefer to have everything in just one panel, I don't think it wouldn't work that way. In that case, we will need to remove one of the buttons, probably "Edit salary allocation" and change the text of the "Request salary" button.

**Comment by sembrestels** [comment]
Checking out the interface again, I think your argument of avoiding an excess of information has a lot of sense. In the case of going for that, I'm concerned about there is no edit allocation button in the request salary panel, and as it is placed in the interface, it seems disconnected from the request salary workflow. What do you think about moving or copying it inside the panel?

On the other hand, if we finally decide to go for just one panel, I think the "Request salary" text button is fine, and we can set as the default allocation the one that the user chose last time.

**Comment by rperez89** [comment]
The request salary will be using the same slider ? Because I am not seeing there how the user is going to select the request percentages, I think that if can be edited later it makes sense to be able to select it at the requesting time right?

**Comment by fioreb** [comment]
> Checking out the interface again, I think your argument of avoiding an excess of information has a lot of sense. In the case of going for that, I'm concerned about there is no edit allocation button in the request salary panel, and as it is placed in the interface, it seems disconnected from the request salary workflow. What do you think about moving or copying it inside the panel?
> 
> On the other hand, if we finally decide to go for just one panel, I think the "Request salary" text button is fine, and we can set as the default allocation the one that the user chose last time.



There is another place where a button is placed inside a side panel? I am concern about that flow because in that case, we need to show new info there and hide the current one, maybe we can have a back option on the top left corner, for the cases the user changes his mind and doesn´t want to modify the salary location and just request it as it is.

I am thinking maybe I can work in a new version, with everything in one place but simplifying the info we are showing, to avoid an excess of information.

**Comment by fioreb** [comment]
> The request salary will be using the same slider ? Because I am not seeing there how the user is going to select the request percentages, I think that if can be edited later it makes sense to be able to select it at the requesting time right?

This is the design for that Ro:
https://user-images.githubusercontent.com/61423083/75819768-f6b98200-5d79-11ea-8e4b-4704402d2769.png

But I'm going to try with only one panel with everything.
Because of checking this again, I think it would be useful for the user to have the see the different amounts there too (not only when he request the salary)

**Comment by fioreb** [comment]
Mmm, this text: "Your split contract will be updated on the blockchain, and you cannot request salary until it’s complete" 

Keeping that in mind: the user can't Edit salary allocation and request for the salary at the same time, is that correct?

**Comment by sembrestels** [comment]
No, I think that this would not be the case. At any moment the _emplyee_ can request their full salary until that moment in time, or get the percentage she choose, and the rest in equity.

**Comment by lkngtn** [comment]
Some feedback:

1) as already discussed, I think it makes sense to combine the request and split into one action if feasible. I like the idea of having the "default" value presented to the user be the same as what they had previously used.

2) We can probably remove the exchange rate column entirely. I think in the current design we would have one entry per asset, but I think it may make sense to instead have 1 entry per withdrawal. We could list the amount of the base asset and the amount of the equity asset in two columns. Perhaps having an additional column for the "split percentage"

3) Im confused by "total transferred" is, I think this may be the total value earned over the lifetime of the employee... but not entirely sure. If it is that im not sure how valuable it is as a metric and might be confusing without being able to convert amounts back to the base asset. I might consider removing it and moving the "balance available" and "salary per period" amounts into their own boxes (on the right?)

4) Assuming we can can combine the split decision into the request salary decision, I think the salary allocation card becomes uneccessary and can be removed.

5) I'm curious to understand if the "export functionality" shown in this is difficult to implement or pretty simple. In practice I don't see it being particularly useful and would avoid implementing it unless it was basically something we get for free from the table component itself.

**Comment by fioreb** [comment]
I worked on the changes we discuss. 

**Main page:**
With the new elements on the table, we need more space so I make some other changes.
I think it would be useful for the user to have the information on how his salary is split into the corresponding boxes too, what do you think?

![Payroll - Main](https://user-images.githubusercontent.com/61423083/76027220-0ae2b800-5f0f-11ea-83c4-faa94bb4df7d.png)


**Request salary:**
![Payroll - Edit split and request salary](https://user-images.githubusercontent.com/61423083/76027213-06b69a80-5f0f-11ea-91d2-1657523547c4.png)

Please let me know your thoughts, thanks!

**Comment by lkngtn** [comment]
Looking good! 

I think we need to find somewhere to indicate the multiplier and vesting settings associated with the equity option. 

In the "Salary allocation" description perhaps we can use the following copy:
> You have the option to receive your salary in a combination of $(Base Asset) or $(Equity asset). The $(Equity asset) allocation is subject to a $(multiplier, eg 2x) and $(12 Month) vesting period with $(3 Month cliff).

How do you feel about making the first card:

Salary:
- Balance Available 
- Monthly Rate

Then have the second box be new:

Equity Option:
- Multiplier
- Vesting Period
- Vesting Cliff

**Comment by fioreb** [comment]
> Looking good!
> 
> I think we need to find somewhere to indicate the multiplier and vesting settings associated with the equity option.
> 
> In the "Salary allocation" description perhaps we can use the following copy:
> 
> > You have the option to receive your salary in a combination of $(Base Asset) or $(Equity asset). The $(Equity asset) allocation is subject to a $(multiplier, eg 2x) and $(12 Month) vesting period with $(3 Month cliff).
> 
> How do you feel about making the first card:
> 
> Salary:
> 
> * Balance Available
> * Monthly Rate
> 
> Then have the second box be new:
> 
> Equity Option:
> 
> * Multiplier
> * Vesting Period
> * Vesting Cliff

Yes perfect, I will work on those changes!

**Comment by fioreb** [comment]
New designs:

**Main page:**
![Payroll - Main](https://user-images.githubusercontent.com/61423083/76102221-6ca62f00-5fae-11ea-9e63-09d6c4a9e7fb.png)

**Request salary:**
![Payroll - Edit split and request salary](https://user-images.githubusercontent.com/61423083/76102209-687a1180-5fae-11ea-8f08-5b161fae7a41.png)

**Comment by lkngtn** [comment]
for the rate I was thinking it would be the pay rate. So like 1 thousand dai a month, not a percentage.

**Comment by lkngtn** [comment]
Oh and we can also remove the info box about the exchange rate changing from the request salary.

**Comment by fioreb** [comment]
> Oh and we can also remove the info box about the exchange rate changing from the request salary.

Sorry, which ones? the gray numbers?

**Comment by lkngtn** [comment]
The one in orange on the signer panel

**Comment by fioreb** [comment]
Ooh, got it! 🤦‍♀️

New designs:

**Main page:**
![Payroll - Main](https://user-images.githubusercontent.com/61423083/76104843-ce689800-5fb2-11ea-9737-ad144773eba3.png)

**Request salary:**
![Payroll - Edit split and request salary](https://user-images.githubusercontent.com/61423083/76104832-c9a3e400-5fb2-11ea-9a5b-37c60a10a64a.png)

**Comment by rperez89** [comment]
Closing since we already have the designs and was implemente the smart contract side on #26
