### ISSUE TITLE
Main dashboard: New equity token icon

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#30]
![Screen Shot 2020-04-08 at 2.27.50 PM.png](https://images.zenhubusercontent.com/5d1a3d0ca91f961fd8457fff/4bf4d2eb-2674-40c3-adfe-311ba16e7f06)

Loving the bee one :) but we need a generic one

**Comment by fioreb** [comment]
Done!
https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=228%3A591

If everything is ok, I will close the issue.
