### ISSUE TITLE
Payday: Reset to 0 the accrual balance if employee request a partial payout

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#32]
When withdrawing salary, the employee need to be able to specify some fraction of the total balance that has accrued in base asset. (eg I've negotiated a rate of 50 dai an hour, I worked 10 hours since last time I request pay, I will request only 500 dai, even if if I technically have permission to withdraw more than that).

So basically we are going to trust on the employees that they are not requesting more than what they should do and if that behaviour is detected the org can take some action against the employee

So in order to allow the employee request less than the max amount accrued we are going to reset the accrued balance as if the employee had withdrawn the full amount.

If for some reason the employee by mistake select less than it should be that needs to be handled within the org members in another way (like a finance transfer)

**Comment by fabriziovigevani** [comment]
closed by #29
