### ISSUE TITLE
Request salary panel: Take into account the vesting counter

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#33]
![Screen Shot 2020-04-08 at 8.03.03 PM.png](https://images.zenhubusercontent.com/5d1a3d0ca91f961fd8457fff/e3e750fc-bbff-41bd-983c-c4ac8d96c522)

Right now we have this beautiful design but if the payroll is configured to work with vestings we need to have a way to display to the user the remaining vestings that he will be able to do with the address provided.

Once the address reach to 50 vestings we need to disable the possibility to choose equity token for the payroll and let the user know that if he wants to be able to be paid with equity token again he needs to change their address.

Also we need to display here the max amount available to be requested and let the employee choose if he wants to request all the amount or less.

**Comment by fioreb** [comment]
I am having some difficulties in showing the max amount that the user has to request, I worked on two options.

**OPTION 1**
I know that putting values ​​in $ is not ideal, but in this way, it works as a common denominator to place the maximum amount that the user can request:
https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=228%3A1740

**OPTION 2:**
In this option, we have separated the maximums. When the user introduce the amount in the ANT input, the value of HONEY appears automatically to the user and vise versa.
https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=299%3A23

(In both cases the bottom values will be modified according to what the user places in the inputs)

I think option 1 is easier for the user to understand and makes the sidepanel look less crowded, but I would like to know your opinons. Thanks :)

**Comment by fioreb** [comment]
Here is the design for the side panel when the user doesn't have the possibility to choose equity token:

https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=293%3A15

**Comment by rperez89** [comment]
> I am having some difficulties in showing the max amount that the user has to request, I worked on two options.
> 
> **OPTION 1**
> I know that putting values ​​in $ is not ideal, but in this way, it works as a common denominator to place the maximum amount that the user can request:
> https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=228%3A1740
> 
> **OPTION 2:**
> In this option, we have separated the maximums. When the user introduce the amount in the ANT input, the value of HONEY appears automatically to the user and vise versa.
> https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=299%3A23
> 
> (In both cases the bottom values will be modified according to what the user places in the inputs)
> 
> I think option 1 is easier for the user to understand and makes the sidepanel look less crowded, but I would like to know your opinons. Thanks :)

Couple of comments, usually we use that yellow warning message after the content.
<img width="450" alt="Screen Shot 2020-04-15 at 10 00 54 PM" src="https://user-images.githubusercontent.com/11763623/79403206-9d419700-7f64-11ea-97fd-1513b53ff1ca.png">

Instead of `Maximum amount to request per month` i would use `Total accrued balance` because is the amount available that you have to request.

For this text  i would use a tooltip somewhere

```You have the option to receive your salary in a combination of $(Base Asset) or $(Equity asset). The $(Equity asset) allocation is subject to a $(multiplier, eg 2x) and $(12 Month) vesting period with $(3 Month cliff).```

**Comment by fioreb** [comment]
Oh! I saw the yellow warning on top on the Tokens figma file, that's why I place it there but I will change it of course! and I will work on the other changes too.

If we remove the USD conversions, how the user will know what to put in the "Amount to request" input? with only one input to add the amount requested, I think we need to have a common denominator for that, otherwise, the user won't know what is he entering in the input.

**Comment by rperez89** [comment]
Ahh i just saw it on the token manager that info component, mmm not sure where we should place it haha.
About the USD, so we will have one denomination Token that it could be DAI, ANT, or whatever and the employee will have a salary based on the token, not usd. So for example the user will have a salary of 5000 ANT so he is always requesting the amount in the denomination token, then if the user decide to get some part in equity  for example 50% ANT and 50% EquityToken and we have a 4X multiplier the user will get 2500 ANT and 10K EquityToken

**Comment by fioreb** [comment]
Perfect Ro! Thanks for the explanation, this solves the problem that I have didn't finding the common denomination for that input.
I will change the designs.

**Comment by lkngtn** [comment]
> and maybe ask @lkngtn about the content. 

I think the content should be okay so long as we can replace the variables with the actual data. 

> And i think that we should remove all the usd conversions. 

Agreed!

**Comment by fioreb** [comment]
Changes are done.
Not sure about the color for the input with the MAX inside, because I could only find it at the Court site, 
but I followed the graphic line of other components.
