### ISSUE TITLE
Mainview: Equity widget

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#47]
[Design](https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=228%3A591)

**Comment by fabriziovigevani** [comment]
Notes on this: Component it's already implemented, we just need to format the vesting parameters and also open the panel when requesting on editing the equity option

**Comment by rperez89** [comment]
> Notes on this: Component it's already implemented, we just need to format the vesting parameters and also open the panel when requesting on editing the equity option

What do you mean by format the vesting parameters fabri?

**Comment by fabriziovigevani** [comment]
e.g `15770000000 seconds` => `6 months`

**Comment by crisog** [comment]
Doing some work on this issue.

- [x] Formatting vesting parameters, converting seconds to months and displaying 'X Month'
- [x] Showing 'no vesting' when vesting length is set to 0
- [ ]  Open the panel when requesting on editing the equity option

<img src="https://user-images.githubusercontent.com/40803711/81492646-87737900-9267-11ea-81d5-6b1d90a85e3f.png" alt="image" width="300" height="300"/>
