### ISSUE TITLE
Design: Small changes accross the app

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#55]
- My payroll: Dataview - remove trx and add it to the action buttons

- My payroll: Dataview - remove status

- Team payroll: Remove salary burn rate widget

- Team payroll: Remove action buttons from dataview

**Comment by fabriziovigevani** [comment]
Already done https://www.figma.com/file/nKZowkSjFJm6yL6ITSEaCw/Payroll?node-id=228%3A0
